<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bats</string>
	</array>
	<key>foldingStartMarker</key>
	<string>\b(if|case)\b|(\{|\b(do)\b)$</string>
	<key>foldingStopMarker</key>
	<string>^\s*(\}|(done|fi|esac)\b)</string>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>Bats</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.shell</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.shell.bats</string>
	<key>uuid</key>
	<string>D001D6FC-04A3-4BB6-9588-A6BCE46DDEDB</string>
</dict>
</plist>
